print("#########################")
print("#                       #")
print("# ATHAYA LAILY SYAFITRI #")
print("#     2310817220008     #")
print("#                       #")
print("#########################")